# Generated by Django 5.1.1 on 2024-09-12 02:09

import my_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[(my_app.models.Category['EVENTS'], 'Events'), (my_app.models.Category['ANNOUNCEMENTS'], 'Announcements'), (my_app.models.Category['HOUSING'], 'Housing'), (my_app.models.Category['EDUCATION'], 'Education'), (my_app.models.Category['VOLUNTEERING'], 'Volunteering'), (my_app.models.Category['RECOMMENDATIONS'], 'Recommendations'), (my_app.models.Category['GENERAL_DISCUSSION'], 'General Discussion'), (my_app.models.Category['HELP_SUPPORT'], 'Help & Support'), (my_app.models.Category['HEALTH_WELLNESS'], 'Health & Wellness'), (my_app.models.Category['POLITICS_LOCAL_ISSUES'], 'Politics & Local Issues'), (my_app.models.Category['TECHNOLOGY'], 'Technology'), (my_app.models.Category['PARENTING_FAMILY'], 'Parenting & Family'), (my_app.models.Category['PETS'], 'Pets'), (my_app.models.Category['LOST_FOUND'], 'Lost & Found'), (my_app.models.Category['FOR_SALE'], 'For Sale')], default='GENERAL_DISCUSSION', max_length=50)),
                ('description', models.TextField(max_length=250)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
