# Generated by Django 5.1.1 on 2024-09-13 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='category',
            field=models.CharField(choices=[('Events', 'Events'), ('Announcements', 'Announcements'), ('Housing', 'Housing'), ('Education', 'Education'), ('Volunteering', 'Volunteering'), ('Recommendations', 'Recommendations'), ('General Discussion', 'General Discussion'), ('Help & Support', 'Help & Support'), ('Health & Wellness', 'Health & Wellness'), ('Politics & Local Issues', 'Politics & Local Issues'), ('Technology', 'Technology'), ('Parenting & Family', 'Parenting & Family'), ('Pets', 'Pets'), ('Lost & Found', 'Lost & Found'), ('For Sale', 'For Sale')], default='General Discussion', max_length=50),
        ),
    ]
