# Generated by Django 5.1.1 on 2024-09-13 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_alter_board_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='category',
            field=models.CharField(choices=[('EVENTS', 'Events'), ('ANNOUNCEMENTS', 'Announcements'), ('HOUSING', 'Housing'), ('EDUCATION', 'Education'), ('VOLUNTEERING', 'Volunteering'), ('RECOMMENDATIONS', 'Recommendations'), ('GENERAL_DISCUSSION', 'General Discussion'), ('HELP_SUPPORT', 'Help & Support'), ('HEALTH_WELLNESS', 'Health & Wellness'), ('POLITICS_LOCAL_ISSUES', 'Politics & Local Issues'), ('TECHNOLOGY', 'Technology'), ('PARENTING_FAMILY', 'Parenting & Family'), ('PETS', 'Pets'), ('LOST_FOUND', 'Lost & Found'), ('FOR_SALE', 'For Sale')], default='General Discussion', max_length=50),
        ),
        migrations.AlterField(
            model_name='board',
            name='date_posted',
            field=models.DateTimeField(),
        ),
    ]
